[package]
name = "hyphae-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
containerd-client = { path = "../../rust-extensions/crates/client" }
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
prost-types = "*"